-- PRODE MUNDIALISTA - SUPABASE
-- Podés ejecutar este archivo completo sin borrar datos.

create extension if not exists pgcrypto;

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  match_no int not null unique,
  round text not null default '16avos',
  team_a text not null,
  team_b text not null,
  starts_at timestamptz,
  real_a int check (real_a is null or real_a >= 0),
  real_b int check (real_b is null or real_b >= 0),
  locked boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.matches add column if not exists went_penalties boolean not null default false;
alter table public.matches add column if not exists advance_winner text check (advance_winner is null or advance_winner in ('A','B'));
alter table public.matches add column if not exists real_pen_a int check (real_pen_a is null or real_pen_a >= 0);
alter table public.matches add column if not exists real_pen_b int check (real_pen_b is null or real_pen_b >= 0);

create table if not exists public.participants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  name_key text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.predictions (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants(id) on delete cascade,
  match_id bigint not null references public.matches(id) on delete cascade,
  pred_a int not null check (pred_a >= 0),
  pred_b int not null check (pred_b >= 0),
  updated_at timestamptz not null default now(),
  unique (participant_id, match_id)
);

alter table public.predictions add column if not exists advance_pick text check (advance_pick is null or advance_pick in ('A','B'));
alter table public.predictions add column if not exists pred_pen_a int check (pred_pen_a is null or pred_pen_a >= 0);
alter table public.predictions add column if not exists pred_pen_b int check (pred_pen_b is null or pred_pen_b >= 0);

-- Si ya había pronósticos cargados sin advance_pick, se completa automáticamente según el resultado pronosticado.
update public.predictions
set advance_pick = case
  when pred_a > pred_b then 'A'
  when pred_b > pred_a then 'B'
  else advance_pick
end
where advance_pick is null;

-- Actualiza updated_at automáticamente cuando cambian los pronósticos.
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_predictions_updated_at on public.predictions;
create trigger trg_predictions_updated_at
before update on public.predictions
for each row execute function public.set_updated_at();

-- Partidos iniciales. Cambiá los nombres desde Supabase si querés.
insert into public.matches (match_no, round, team_a, team_b)
values
  (1, '16avos', 'Alemania', '3A/B/C/D/F'),
  (2, '16avos', '1I', '3C/D/F/G/H'),
  (3, '16avos', 'Sudáfrica', 'Canadá'),
  (4, '16avos', 'Países Bajos', 'Marruecos'),
  (5, '16avos', '2K', '2L'),
  (6, '16avos', '1H', '2J'),
  (7, '16avos', 'Estados Unidos', 'Bosnia Herzegovina'),
  (8, '16avos', '1G', '3A/E/H/I/J'),
  (9, '16avos', 'Brasil', 'Japón'),
  (10, '16avos', 'Costa de Marfil', '2I'),
  (11, '16avos', 'México', '3C/E/F/H/I'),
  (12, '16avos', '1L', '3E/H/I/J/K'),
  (13, '16avos', 'Argentina', '2H'),
  (14, '16avos', 'Australia', '2G'),
  (15, '16avos', 'Suiza', '3E/F/G/I/J'),
  (16, '16avos', '1K', '3D/E/I/J/L')
on conflict (match_no) do nothing;

-- Seguridad básica.
alter table public.matches enable row level security;
alter table public.participants enable row level security;
alter table public.predictions enable row level security;

-- Limpiar políticas si ya existían.
drop policy if exists "Lectura publica matches" on public.matches;
drop policy if exists "Lectura publica participants" on public.participants;
drop policy if exists "Alta publica participants" on public.participants;
drop policy if exists "Lectura publica predictions" on public.predictions;
drop policy if exists "Alta pronosticos abiertos" on public.predictions;
drop policy if exists "Editar pronosticos abiertos" on public.predictions;

-- Todos pueden ver partidos, participantes y pronósticos para que funcione el ranking.
create policy "Lectura publica matches"
on public.matches for select
using (true);

create policy "Lectura publica participants"
on public.participants for select
using (true);

create policy "Alta publica participants"
on public.participants for insert
with check (true);

create policy "Lectura publica predictions"
on public.predictions for select
using (true);

-- Se pueden cargar/editar pronósticos solo mientras el partido no esté bloqueado y no tenga resultado real.
create policy "Alta pronosticos abiertos"
on public.predictions for insert
with check (
  advance_pick in ('A','B')
  and exists (
    select 1 from public.matches m
    where m.id = predictions.match_id
      and m.locked = false
      and m.real_a is null
      and m.real_b is null
  )
);

create policy "Editar pronosticos abiertos"
on public.predictions for update
using (
  exists (
    select 1 from public.matches m
    where m.id = predictions.match_id
      and m.locked = false
      and m.real_a is null
      and m.real_b is null
  )
)
with check (
  advance_pick in ('A','B')
  and exists (
    select 1 from public.matches m
    where m.id = predictions.match_id
      and m.locked = false
      and m.real_a is null
      and m.real_b is null
  )
);

grant usage on schema public to anon, authenticated;
grant select on public.matches, public.participants, public.predictions to anon, authenticated;
grant insert on public.participants, public.predictions to anon, authenticated;
grant update on public.predictions to anon, authenticated;
