-- PRODE MUNDIALISTA - SUPABASE
-- 1) Crear un proyecto en Supabase.
-- 2) Ir a SQL Editor.
-- 3) Pegar y ejecutar todo este archivo.

create extension if not exists pgcrypto;

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  match_no int not null unique,
  round text not null default '16avos',
  team_a text not null,
  team_b text not null,
  starts_at timestamptz,
  real_a int check (real_a is null or real_a >= 0),
  real_b int check (real_b is null or real_b >= 0),
  locked boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.participants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  name_key text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.predictions (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants(id) on delete cascade,
  match_id bigint not null references public.matches(id) on delete cascade,
  pred_a int not null check (pred_a >= 0),
  pred_b int not null check (pred_b >= 0),
  updated_at timestamptz not null default now(),
  unique (participant_id, match_id)
);

-- Actualiza updated_at automáticamente cuando cambian los pronósticos.
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_predictions_updated_at on public.predictions;
create trigger trg_predictions_updated_at
before update on public.predictions
for each row execute function public.set_updated_at();

-- Partidos iniciales. Cambiá los nombres desde Supabase si querés.
insert into public.matches (match_no, round, team_a, team_b)
values
  (1, '16avos', 'Egipto', 'Croacia'),
  (2, '16avos', 'Equipo 3', 'Equipo 4'),
  (3, '16avos', 'Equipo 5', 'Equipo 6'),
  (4, '16avos', 'Equipo 7', 'Equipo 8'),
  (5, '16avos', 'Equipo 9', 'Equipo 10'),
  (6, '16avos', 'Equipo 11', 'Equipo 12'),
  (7, '16avos', 'Equipo 13', 'Equipo 14'),
  (8, '16avos', 'Equipo 15', 'Equipo 16'),
  (9, '16avos', 'Equipo 17', 'Equipo 18'),
  (10, '16avos', 'Equipo 19', 'Equipo 20'),
  (11, '16avos', 'Equipo 21', 'Equipo 22'),
  (12, '16avos', 'Equipo 23', 'Equipo 24'),
  (13, '16avos', 'Equipo 25', 'Equipo 26'),
  (14, '16avos', 'Equipo 27', 'Equipo 28'),
  (15, '16avos', 'Equipo 29', 'Equipo 30'),
  (16, '16avos', 'Equipo 31', 'Equipo 32')
on conflict (match_no) do nothing;

-- Seguridad básica.
alter table public.matches enable row level security;
alter table public.participants enable row level security;
alter table public.predictions enable row level security;

-- Limpiar políticas si ya existían.
drop policy if exists "Lectura publica matches" on public.matches;
drop policy if exists "Lectura publica participants" on public.participants;
drop policy if exists "Alta publica participants" on public.participants;
drop policy if exists "Lectura publica predictions" on public.predictions;
drop policy if exists "Alta pronosticos abiertos" on public.predictions;
drop policy if exists "Editar pronosticos abiertos" on public.predictions;

-- Todos pueden ver partidos, participantes y pronósticos para que funcione el ranking.
create policy "Lectura publica matches"
on public.matches for select
using (true);

create policy "Lectura publica participants"
on public.participants for select
using (true);

create policy "Alta publica participants"
on public.participants for insert
with check (true);

create policy "Lectura publica predictions"
on public.predictions for select
using (true);

-- Se pueden cargar/editar pronósticos solo mientras el partido no esté bloqueado y no tenga resultado real.
create policy "Alta pronosticos abiertos"
on public.predictions for insert
with check (
  exists (
    select 1 from public.matches m
    where m.id = predictions.match_id
      and m.locked = false
      and m.real_a is null
      and m.real_b is null
  )
);

create policy "Editar pronosticos abiertos"
on public.predictions for update
using (
  exists (
    select 1 from public.matches m
    where m.id = predictions.match_id
      and m.locked = false
      and m.real_a is null
      and m.real_b is null
  )
)
with check (
  exists (
    select 1 from public.matches m
    where m.id = predictions.match_id
      and m.locked = false
      and m.real_a is null
      and m.real_b is null
  )
);

grant usage on schema public to anon, authenticated;
grant select on public.matches, public.participants, public.predictions to anon, authenticated;
grant insert on public.participants, public.predictions to anon, authenticated;
grant update on public.predictions to anon, authenticated;
